export const complejos = [
  {
    id: "1",
    name: "Chillan soccer",
    country: "Chile",
    city: "Chillan",
    address: "Av. Libertad 1234",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVczhyCyS1OKuNQMh_wD6E4tSMUGcyA_O3MA&s",
    stars: 4.2,
  },
  {
    id: "9",
    name: "Polideportivo La Liga",
    country: "Chile",
    city: "Chillan",
    address: "San Jorge, N-45",
    image_url:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg7ZlAmo7tpgzbRveNDNiBhOOfJsYvOqYJ4oa3LThr4XtMTnRq0o2A9awp4u7tSghkeD4Rc3F2nkKaQ409E7dSkE2tJsE8Y7KZSd0CAMnLHputhO35NBpJraiLQhiXifcx5nIQX/w1200-h630-p-k-no-nu/bora+futbol.jpg",
    stars: 4.5,
  },
  {
    id: "10",
    name: "Complejo Quilamapu",
    country: "Chile",
    city: "Chillan",
    address: "Calle Flores Millán 1005",
    image_url: null,
    stars: 3.7,
  },
  {
    id: "11",
    name: "Canchas Las Mariposas",
    country: "Chile",
    city: "Chillan",
    address: "Km 14, Camino Las Mariposas",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "2",
    name: "Santiago soccer",
    country: "Chile",
    city: "Santiago",
    address: "Av. Providencia 5678",
    image_url:
      "https://cdn.pixabay.com/photo/2016/11/29/04/17/football-1867161_1280.jpg",
    stars: 3.8,
  },
  {
    id: "3",
    name: "Valparaiso soccer",
    country: "Chile",
    city: "Valparaiso",
    address: "Av. España 9101",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "4",
    name: "Concepcion soccer",
    country: "Chile",
    city: "Concepcion",
    address: "Av. O'Higgins 1122",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "5",
    name: "La Serena soccer",
    country: "Chile",
    city: "La Serena",
    address: "Av. del Mar 3344",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "6",
    name: "Antofagasta soccer",
    country: "Chile",
    city: "Antofagasta",
    address: "Av. Angamos 5566",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "7",
    name: "Temuco soccer",
    country: "Chile",
    city: "Temuco",
    address: "Av. Alemania 7788",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "8",
    name: "Puerto Montt soccer",
    country: "Chile",
    city: "Puerto Montt",
    address: "Av. Costanera 9900",
    image_url:
      "https://cdn.pixabay.com/photo/2017/06/13/22/42/soccer-2406153_1280.jpg",
    stars: 4.4,
  },
];
