export const complejos = [
  {
    id: "9",
    name: "Polideportivo La Liga",
    country: "Chile",
    city: "Chillan",
    address: "San Jorge, N-45",
    image_url:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg7ZlAmo7tpgzbRveNDNiBhOOfJsYvOqYJ4oa3LThr4XtMTnRq0o2A9awp4u7tSghkeD4Rc3F2nkKaQ409E7dSkE2tJsE8Y7KZSd0CAMnLHputhO35NBpJraiLQhiXifcx5nIQX/w1200-h630-p-k-no-nu/bora+futbol.jpg",
    stars: 4.5,
  },
  {
    id: "10",
    name: "Complejo Quilamapu",
    country: "Chile",
    city: "Chillan",
    address: "Calle Flores Millán 1005",
    image_url: null,
    stars: 3.7,
  },
  {
    id: "11",
    name: "Canchas Las Mariposas",
    country: "Chile",
    city: "Chillan",
    address: "Km 14, Camino Las Mariposas",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "2",
    name: "Santiago soccer",
    country: "Chile",
    city: "Santiago",
    address: "Av. Providencia 5678",
    image_url:
      "https://cdn.pixabay.com/photo/2016/11/29/04/17/football-1867161_1280.jpg",
    stars: 3.8,
  },
  {
    id: "3",
    name: "Valparaiso soccer",
    country: "Chile",
    city: "Valparaiso",
    address: "Av. España 9101",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "4",
    name: "Concepcion soccer",
    country: "Chile",
    city: "Concepcion",
    address: "Av. O'Higgins 1122",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "5",
    name: "La Serena soccer",
    country: "Chile",
    city: "La Serena",
    address: "Av. del Mar 3344",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "6",
    name: "Antofagasta soccer",
    country: "Chile",
    city: "Antofagasta",
    address: "Av. Angamos 5566",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "7",
    name: "Temuco soccer",
    country: "Chile",
    city: "Temuco",
    address: "Av. Alemania 7788",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "8",
    name: "Puerto Montt soccer",
    country: "Chile",
    city: "Puerto Montt",
    address: "Av. Costanera 9900",
    image_url:
      "https://cdn.pixabay.com/photo/2017/06/13/22/42/soccer-2406153_1280.jpg",
    stars: 4.4,
  },
  {
    id: "1",
    name: "Chillan soccer",
    country: "Chile",
    city: "Chillan",
    address: "Av. Libertad 1234",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVczhyCyS1OKuNQMh_wD6E4tSMUGcyA_O3MA&s",
    stars: 4.2,
  },
  {
    id: "12",
    name: "Centro Deportivo Chillan 1",
    country: "Chile",
    city: "Chillan",
    address: "Av. Central 101",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "13",
    name: "Cancha Sur Santiago",
    country: "Chile",
    city: "Santiago",
    address: "Calle Sur 202",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "14",
    name: "Deportivo Costanera",
    country: "Chile",
    city: "Puerto Montt",
    address: "Ruta 5 3300",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "15",
    name: "Complejo Norte Quilamapu",
    country: "Chile",
    city: "Chillan",
    address: "Pasaje Norte 55",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "16",
    name: "Estadio La Serena Sur",
    country: "Chile",
    city: "La Serena",
    address: "Av. Pacifico 1122",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "17",
    name: "Complejo Angamos 2",
    country: "Chile",
    city: "Antofagasta",
    address: "Av. Angamos 888",
    image_url: null,
    stars: 4.4,
  },
  {
    id: "18",
    name: "Cancha O'Higgins Park",
    country: "Chile",
    city: "Concepcion",
    address: "Parque O'Higgins 7",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "19",
    name: "Estadio Playa Norte",
    country: "Chile",
    city: "Valparaiso",
    address: "Camino Playa 99",
    image_url: null,
    stars: 3.8,
  },
  {
    id: "20",
    name: "Centro Deportivo Temuco Norte",
    country: "Chile",
    city: "Temuco",
    address: "Av. Araucanía 4455",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "21",
    name: "Estadio Vecinal Chillan",
    country: "Chile",
    city: "Chillan",
    address: "Pasaje Uno 300",
    image_url: null,
    stars: 3.7,
  },
  {
    id: "22",
    name: "Polideportivo Santiago Sur",
    country: "Chile",
    city: "Santiago",
    address: "Av. Alameda 1001",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "23",
    name: "Complejo Futbol Marítimo",
    country: "Chile",
    city: "Valparaiso",
    address: "Av. Costanera 321",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "24",
    name: "Cancha Techada Serena",
    country: "Chile",
    city: "La Serena",
    address: "Calle Norte 909",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "25",
    name: "Futbol Total Temuco",
    country: "Chile",
    city: "Temuco",
    address: "Camino Viejo 123",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "26",
    name: "Complejo Deportivo La Perla",
    country: "Chile",
    city: "Antofagasta",
    address: "Av. Pacífico 1200",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "27",
    name: "Estadio Concepción Viejo",
    country: "Chile",
    city: "Concepcion",
    address: "Calle Nueva 111",
    image_url: null,
    stars: 3.8,
  },
  {
    id: "28",
    name: "Cancha Este Chillan",
    country: "Chile",
    city: "Chillan",
    address: "Av. Este 222",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "29",
    name: "Futbol Urbano Santiago",
    country: "Chile",
    city: "Santiago",
    address: "Calle Mayor 889",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "30",
    name: "Soccer Park Valpo",
    country: "Chile",
    city: "Valparaiso",
    address: "Av. Principal 100",
    image_url: null,
    stars: 4.4,
  },
  {
    id: "31",
    name: "Estadio Regional Serena",
    country: "Chile",
    city: "La Serena",
    address: "Ruta 43, km 10",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "32",
    name: "Deportivo Estrella Temuco",
    country: "Chile",
    city: "Temuco",
    address: "Av. Estrella 555",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "33",
    name: "Cancha Norte Antofa",
    country: "Chile",
    city: "Antofagasta",
    address: "Av. Norte 910",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "34",
    name: "Concepción FC",
    country: "Chile",
    city: "Concepcion",
    address: "Calle Central 404",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "35",
    name: "Cancha Oriente Chillan",
    country: "Chile",
    city: "Chillan",
    address: "Oriente 789",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "36",
    name: "Centro Deportivo Alameda",
    country: "Chile",
    city: "Santiago",
    address: "Alameda 2000",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "37",
    name: "Valpo Sur Canchas",
    country: "Chile",
    city: "Valparaiso",
    address: "Av. Sur 122",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "38",
    name: "La Serena Norte",
    country: "Chile",
    city: "La Serena",
    address: "Pasaje Norte 1000",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "39",
    name: "Estadio Ñielol",
    country: "Chile",
    city: "Temuco",
    address: "Calle Ñielol 300",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "40",
    name: "Antofagasta Arena",
    country: "Chile",
    city: "Antofagasta",
    address: "Arena 707",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "41",
    name: "Estadio Universidad Conce",
    country: "Chile",
    city: "Concepcion",
    address: "Campus UdeC",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "42",
    name: "Complejo Deportivo Chillan Sur",
    country: "Chile",
    city: "Chillan",
    address: "Sur 300",
    image_url: null,
    stars: 3.8,
  },
  {
    id: "43",
    name: "Futbol Club Santiago Norte",
    country: "Chile",
    city: "Santiago",
    address: "Ruta Norte 77",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "44",
    name: "Cancha Playa Ancha",
    country: "Chile",
    city: "Valparaiso",
    address: "Playa Ancha 444",
    image_url: null,
    stars: 4.4,
  },
  {
    id: "45",
    name: "La Serena FC",
    country: "Chile",
    city: "La Serena",
    address: "Centro 100",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "46",
    name: "Complejo Deportivo Llaima",
    country: "Chile",
    city: "Temuco",
    address: "Llaima 1010",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "47",
    name: "Antofagasta FC 2",
    country: "Chile",
    city: "Antofagasta",
    address: "Estadio 900",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "48",
    name: "Estadio Collao",
    country: "Chile",
    city: "Concepcion",
    address: "Collao 500",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "49",
    name: "Cancha 12 Chillan",
    country: "Chile",
    city: "Chillan",
    address: "Calle 12 212",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "50",
    name: "Estadio Sur Santiago",
    country: "Chile",
    city: "Santiago",
    address: "Camino Sur 345",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "51",
    name: "Valpo Norte Futbol",
    country: "Chile",
    city: "Valparaiso",
    address: "Calle Norte 12",
    image_url: null,
    stars: 3.7,
  },
  {
    id: "52",
    name: "Estadio Ciudad Serena",
    country: "Chile",
    city: "La Serena",
    address: "Centro Sur 901",
    image_url: null,
    stars: 4.4,
  },
  {
    id: "53",
    name: "Complejo Futbol Temuco",
    country: "Chile",
    city: "Temuco",
    address: "Camino Central 888",
    image_url: null,
    stars: 4.2,
  },
  {
    id: "54",
    name: "Complejo Bahía Antofa",
    country: "Chile",
    city: "Antofagasta",
    address: "Bahía 111",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "55",
    name: "Centro Futbol Concepcion 2",
    country: "Chile",
    city: "Concepcion",
    address: "Sur 456",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "56",
    name: "Deportivo Futuro Chillan",
    country: "Chile",
    city: "Chillan",
    address: "Futuro 123",
    image_url: null,
    stars: 4.1,
  },
  {
    id: "57",
    name: "Estadio Central Santiago",
    country: "Chile",
    city: "Santiago",
    address: "Centro 777",
    image_url: null,
    stars: 4.3,
  },
  {
    id: "58",
    name: "Cancha Estrella Valpo",
    country: "Chile",
    city: "Valparaiso",
    address: "Estrella 101",
    image_url: null,
    stars: 4.5,
  },
  {
    id: "59",
    name: "Cancha Pacífico Serena",
    country: "Chile",
    city: "La Serena",
    address: "Pacífico 456",
    image_url: null,
    stars: 3.9,
  },
  {
    id: "60",
    name: "Futbol Araucanía Temuco",
    country: "Chile",
    city: "Temuco",
    address: "Av. Sur 980",
    image_url: null,
    stars: 4.0,
  },
  {
    id: "61",
    name: "Antofagasta Norte",
    country: "Chile",
    city: "Antofagasta",
    address: "Norte 789",
    image_url: null,
    stars: 4.2,
  },
];
